index:
  path: /
  controller: App\Controller\HomeController::indexAction

change_password:
  path: /wachtwoord-wijzigen/
  methods: [GET, POST]
  controller: App\Controller\SecurityController::changePasswordAction
